someth = str(input('type something: '))

print('The primitive type of this value is? ', type(someth))
print('Does it have space? ', someth.isspace())
print('Is it a number? ', someth.isnumeric())
print('Is it an alphabetic? ', someth.isalpha())
print('Is it alphabet and number? ', someth.isalnum())
print('Is this a capital letter? ', someth.isupper())
print('Is this a lowercase letter? ', someth.islower())
print('Is this a name? ', someth.istitle())
